const inversePerpetual = { BTCUSD: "BTCUSD", ETHUSD: "ETHUSD", EOSUSD: "EOSUSD", XRPUSD: "XRPUSD" }
const usdtPerpetual = {
    BTCUSDT: "BTCUSDT", ETHUSDT: "ETHUSDT", EOSUSDT: "EOSUSDT", XRPUSDT: "XRPUSDT",
    BCHUSDT: "BCHUSDT", LTCUSDT: "LTCUSDT", LINKUSDT: "LINKUSDT", XTZUSDT: "XTZUSDT",
    ADAUSDT: "ADAUSDT", DOTUSDT: "DOTUSDT", UNIUSDT: "UNIUSDT", XEMUSDT: "XEMUSDT",
    SUSHIUSDT: "SUSHIUSDT", AAVEUSDT: "AAVEUSDT", DOGEUSDT: "DOGEUSDT", MATICUSDT: "MATICUSDT",
    ETCUSDT: "ETCUSDT", BNBUSDT: "BNBUSDT", FILUSDT: "FILUSDT", SOLUSDT: "SOLUSDT"
}

const inverse = ["BTCUSD", "ETHUSD", "EOSUSD", "XRPUSD"]
const usdtPerp = ["BTCUSDT", "ETHUSDT", "EOSUSDT", "XRPUSDT", "BCHUSDT", "LTCUSDT", "LINKUSDT", "XTZUSDT", "ADAUSDT", "DOTUSDT", "UNIUSDT", "XEMUSDT", "SUSHIUSDT", "AAVEUSDT", "DOGEUSDT", "MATICUSDT", "ETCUSDT", "BNBUSDT", "FILUSDT", "SOLUSDT"]

export {
    inverse, usdtPerp
}